# Site settings
title: Jacob Harris
email: jacob.patrick.harris@gmail.com
url: https://ahoy1.github.io
description: "Front End Web Developer based in Brooklyn. I love clean code, playful CSS, and good food."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Jacob Harris
  email: Get In Touch
  social: I'm Here Too!

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/alligator_music
  - title: facebook
    url: https://www.facebook.com/jacob.harris.9655
  - title: codepen
    url: http://codepen.io/ahoy/
  - title: github
    url: http://github.com/ahoy1

# email address 
email: 
  - line: jacob.patrick.harris@gmail.com

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty
